version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: user-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_database
    ports:
      - "5431:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-processing-service-network

volumes:
  postgres_data:

networks:
  order-processing-service-network:
    driver: bridge
